### ISSUE TITLE
AppsAdapter.java line 110

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#152]
#### in com.itachi1706.cheesecakeutilities.Modules.ListApplications.RecyclerAdapters.AppsAdapter.getCustomStringForElement

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/59e44f4f61b02d480da61623?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/59e44f4f61b02d480da61623?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by itachi1706** [comment]
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index -1, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.Arrays$ArrayList.get(Arrays.java:66)
       at com.itachi1706.cheesecakeutilities.Modules.ListApplications.RecyclerAdapters.AppsAdapter.getCustomStringForElement(AppsAdapter.java:110)
       at com.turingtechnologies.materialscrollbar.CustomIndicator.getTextElement(CustomIndicator.java:37)
       at com.turingtechnologies.materialscrollbar.CustomIndicator.getTextElement(CustomIndicator.java:26)
       at com.turingtechnologies.materialscrollbar.Indicator.setText(Indicator.java:141)
       at com.turingtechnologies.materialscrollbar.ScrollingUtilities.scrollHandleAndIndicator(ScrollingUtilities.java:71)
       at com.turingtechnologies.materialscrollbar.MaterialScrollBar.onDown(MaterialScrollBar.java:739)
       at com.turingtechnologies.materialscrollbar.TouchScrollBar$2.onTouch(TouchScrollBar.java:81)
       at android.view.View.dispatchTouchEvent(View.java:9481)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2660)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2304)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2454)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1773)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2798)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2415)
       at android.view.View.dispatchPointerEvent(View.java:9721)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4741)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4599)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4104)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4157)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4123)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4269)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4131)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4326)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4104)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4157)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4123)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4131)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4104)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6558)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6532)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6475)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6730)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:5763)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by itachi1706** [comment]
guess fix in #146 didn't really work lol

**Comment by itachi1706** [comment]
reverted #146 in 41b5862a
