### ISSUE TITLE
Crash Log when dismissing Notification (Quiet Hour Revamp)

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#257]
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: FATAL EXCEPTION: main
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: Process: com.itachi1706.cheesecakeutilities, PID: 23147
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentTransaction androidx.fragment.app.FragmentManager.beginTransaction()' on a null object reference
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:219)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:191)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at androidx.biometrics.FingerprintDialogFragment.handleDismissDialog(FingerprintDialogFragment.java:335)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at androidx.biometrics.FingerprintDialogFragment$H.handleMessage(FingerprintDialogFragment.java:100)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6759)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-01 01:39:53.404 10276 23147 23147 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: FATAL EXCEPTION: main
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: Process: com.itachi1706.cheesecakeutilities, PID: 8700
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.Receivers.DeleteNotificationIntent: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3346)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6759)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.Receivers.DeleteNotificationIntent.onReceive(DeleteNotificationIntent.java:24)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3335)
01-01 10:22:01.363 10276  8700  8700 E AndroidRuntime: 	... 8 more

**Comment by itachi1706** [comment]
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: FATAL EXCEPTION: main
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: Process: com.itachi1706.cheesecakeutilities, PID: 29843
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.Receivers.DeleteNotificationIntent: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3346)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6759)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.Receivers.DeleteNotificationIntent.onReceive(DeleteNotificationIntent.java:24)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3335)
01-02 00:53:41.740 10276 29843 29843 E AndroidRuntime: 	... 8 more

**Comment by itachi1706** [comment]
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: FATAL EXCEPTION: main
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: Process: com.itachi1706.cheesecakeutilities, PID: 26156
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.Receivers.DeleteNotificationIntent: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3346)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6759)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.Receivers.DeleteNotificationIntent.onReceive(DeleteNotificationIntent.java:24)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3335)
01-02 09:46:02.949 10276 26156 26156 E AndroidRuntime: 	... 8 more

**Comment by itachi1706** [comment]
These are the logs found. Right now its not released as a release yet which is probably why it is not triggered. Also it does not appear on Crashylytics as its not in the main process. We might look into invoking Crashlytics in subprocesses as well to eliminate this scenario tbh
