### ISSUE TITLE
ConnectivityQuietHoursActivity.java line 147

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#268]
#### in com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.ConnectivityQuietHoursActivity.toggleConnectivitySwitch

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/5c7962ddf8b88c29638f8abe?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/5c7962ddf8b88c29638f8abe?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by itachi1706** [comment]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itachi1706.cheesecakeutilities/com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.ConnectivityQuietHoursActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AlarmManager.cancel(android.app.PendingIntent)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2875)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2950)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AlarmManager.cancel(android.app.PendingIntent)' on a null object reference
       at com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.ConnectivityQuietHoursActivity.toggleConnectivitySwitch(ConnectivityQuietHoursActivity.java:147)
       at com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.ConnectivityQuietHoursActivity.lambda$initEnableToggles$0(ConnectivityQuietHoursActivity.java:130)
       at com.itachi1706.cheesecakeutilities.Modules.ConnectivityQuietHours.-$$Lambda$ConnectivityQuietHoursActivity$3Qa14F11qUkc3sUJ1oM4P_8_jV0.onCheckedChanged(Unknown Source:18)
       at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
       at androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1064)
       at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:566)
       at android.view.View.dispatchRestoreInstanceState(View.java:17707)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3803)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3803)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3803)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3803)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3803)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3803)
       at android.view.View.restoreHierarchyState(View.java:17685)
       at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2158)
       at android.app.Activity.onRestoreInstanceState(Activity.java:1101)
       at android.app.Activity.performRestoreInstanceState(Activity.java:1056)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1260)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2848)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2950)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
