### ISSUE TITLE
MSLData.java line 3

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#296]
#### in com.itachi1706.cheesecakeutilities.Modules.MSLIntegration.model.MSLData$Subjects.getGuid

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/5cdafca5f8b88c2963e987e3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/5cdafca5f8b88c2963e987e3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by itachi1706** [comment]
Fatal Exception: java.lang.NullPointerException: throw with null exception
       at com.itachi1706.cheesecakeutilities.Modules.MSLIntegration.model.MSLData$Subjects.getGuid(MSLData.java:3)
       at com.itachi1706.cheesecakeutilities.Modules.MSLIntegration.SyncMSLService.parseMSLData(SyncMSLService.java:262)
       at com.itachi1706.cheesecakeutilities.Modules.MSLIntegration.SyncMSLService.access$600(SyncMSLService.java:70)
       at com.itachi1706.cheesecakeutilities.Modules.MSLIntegration.SyncMSLService$MSLServiceReceiver.onReceive(SyncMSLService.java:477)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
