### ISSUE TITLE
LyricNotificationListener.java line 185

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#298]
#### in com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.saveImageTmpAndGetUri

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/5cdbab72f8b88c2963f3f982?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/itachi1706s-projects/android/apps/com.itachi1706.cheesecakeutilities/issues/5cdbab72f8b88c2963f3f982?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by itachi1706** [comment]
```
Fatal Exception: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.itachi1706.cheesecakeutilities/cache/images_cache/albumart.png
       at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
       at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
       at com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.saveImageTmpAndGetUri(LyricNotificationListener.java:185)
       at com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.sendBroadcastData(LyricNotificationListener.java:163)
       at com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.updateData(LyricNotificationListener.java:96)
       at com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.processController(LyricNotificationListener.java:85)
       at com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.scanForControllers(LyricNotificationListener.java:65)
       at com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.processNotification(LyricNotificationListener.java:143)
       at com.itachi1706.cheesecakeutilities.Modules.LyricFinder.LyricNotificationListener.onNotificationPosted(LyricNotificationListener.java:126)
       at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:317)
       at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:1826)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

**Comment by itachi1706** [comment]
Probably caused by me updating the manifest fileprovider authority but not updating it in code. Whoops
